teams_url =  "https://statsapi.web.nhl.com/api/v1/teams"
people_url =  "https://statsapi.web.nhl.com/api/v1/people/"
stats_single_season_url = "/stats?stats=statsSingleSeason&season="
season1 = "20162017"
season2 = "20172018"
mtl_roster_ep = "/8?expand=team.roster&season="
jp_get_names = "teams[0].roster.roster[].person[].id"
jp_get_points = "stats[].splits[].stat.points"
